### ISSUE TITLE
Docstring

### ISSUE THREAD

**Issue by matthieuchoplin** [dennyb87/pycity#3]
It is good to use docstring.
Maybe you can try to use doctest (what we saw in the course).

What you can do, if you are not using pycharm, is add the following at the end of your program:

```
import doctest
doctest.testmod()
```

If you want to use doctest to test your code, I recommend that you read https://docs.python.org/3.5/library/doctest.html

**Comment by dennyb87** [comment]
Doctest added where it was possible.
